### ISSUE TITLE
Memory usage increase

### ISSUE THREAD

**Issue by Blacknet-es** [GeniusesOfSymfony/WebSocketBundle#140]
When i launch the websocket service memory used is about 50MB.
After 3 or 4 days the memory increases to 300 ~ 350 Mb.
After a week websocket collapse all server and the process dies.

Note: The memory is increased even if the socket does not have requests.

Any idea? Thank you!!!

**Comment by ProPheT777** [comment]
Hey, 

Have you checkout this https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/ShipInProduction.md#fight-against-memory-leak-

**Comment by TheFamousPG** [comment]
I have the same problem.
I launch the server in production environnement, 
https://i.gyazo.com/00e5d9847dc6aba3c179d140b41e3427.png

And after few hours, tchat server stop working.
I don't know how to check fingers_crossed and why the problem come from my code, because it's just after launching the server.
