### ISSUE TITLE
Synchronize Sessions

### ISSUE THREAD

**Issue by novacp** [GeniusesOfSymfony/WebSocketBundle#147]
Example. User logs out in another tab by /logout route or clearing his cache. The Symfony session tells me that the user is now anonymous / not authenticated anymore, but the Websocket session still tells me the user is logged in. 

This means, that when a user has still his browser opened, he has still access to the connected websocket channels and receives messages to it. On the other side, the cookie is destroyed, and so no one can hijack the session.

As I read, it is not possible to "synchronize" the session. So my question: Is it ok to let the connection opened in this case? I don't see any way on how to close the connection when cache gets cleared. Cookie is only sent once during handshake..

**Comment by aleksa2808** [comment]
Me and a friend are trying to get past this issue as well, or at least to prevent the session from expiring during a WS connection, like it's mentioned by Venzon in #81.

The cause of the issue is that Ratchet saves the session **only once**, during the onOpen call, and stores it for later use. It never checks the proper session again, which, for me, is located on a redis server, in order to be shared between web and ws servers.

For a solution, I can only imagine that you do it manually. :/ In my case that means that I should use the cookie information I obtain on WS connection to poll redis about the existence of the obtained session.

Have you made better progress with your issue perhaps?

**Comment by novacp** [comment]
How would you want to poll for an existing session of another client that
receives a notification from an action of a client? This is not possible.
In addition, this is not a ratchet "Problem" that the session gets
synchronized only once during handshake, it is the nature of websockets
that there is only one initial request. For me,there is logically no way to
synchronize the session. The key is, that you cannot avoid a user who
cleared e.g. the session cookie by himself to receive / stay in the
websocket channel . In fact,the cookie clear example is the only way where
the connection stays open and you cannot do anything.

When a user gets a timeout of my server or logs out, I simply close the
connection. When it comes to Browser session clear by Client, there is no
reliable solution by thinking logically and not exhausting the session
cookie by removing the http only flag
Am 27.05.2016 4:00 vorm. schrieb "aleksa2808" <notifications@github.com>:

**Comment by slmcncb** [comment]
I'm looking for a solution. Is there any progress?

**Comment by novacp** [comment]
There is no solution - logically - without exposing the session cookie.

**Comment by iKonrad** [comment]
@novacp Do you mean logout handler on the server side or client side? Could you elaborate on this please? Just trying to get the same thing working but no luck so far.
