### ISSUE TITLE
Request: Documentation about real-life usage in private chat (or notifications)

### ISSUE THREAD

**Issue by gittix09** [GeniusesOfSymfony/WebSocketBundle#19]
It would be nice if someone could write a bit of documentation about the logic behind a private chat / notification system. Use Whatsup as a reference. Imagine that you want to build a simplified version of it.
Code is NOT strictly required, I think that what is really important is the LOGIC behind it:
- mysql database structure (to easily fetch the latest conversations)
- how to manage new/old rooms and subscriptions
- what happens when a user location changes to another page of your website
- what needs to happen when a user logs in (automaticly subscribe him to all his previous rooms??)
- what happens when user A starts a new conversation with user B (can I subscribe user B to the new conversation form server side?? Will user B receive all the messages published by user A in the new room??)

These are just SOME examples.... just try to think about all the major issues you need to address when creating a basic private chat using a pub/sub system.

There are also some questions on Stackoverflow about this problem. For example:
http://stackoverflow.com/questions/28937843/symfon2-websocketbundle-simple-private-and-group-chat-database-schema-and

**Comment by ProPheT777** [comment]
Well I think I will start a tech blog to give basic concret implementation about this bundle (real time notification, chat etc) because a lot of people are asking me.

Currently i'm working on Real time Notification (https://github.com/GeniusesOfSymfony/NotificationBundle & https://github.com/GeniusesOfSymfony/NotificationAngularApp) and it's take me a lot of time because it's a bit complicated :D.

After this bundle release I will start ChatBundle may be with XMPP protocol over Websocket.

**Comment by gittix09** [comment]
Great!! I will definitely follow these 2 projects. Good luck and thank you very much for replying
