### ISSUE TITLE
Question : Ship in production

### ISSUE THREAD

**Issue by michaeld23** [GeniusesOfSymfony/WebSocketBundle#190]
Hello everybody, 

First of all, thank you for this interesting and useful bundle.
I have tested this in local environment. Everything works perfectly.

Now I need to test it on production and I would like to know if you have any procedure or recommendations for the following configuration :

1- There will be two distinct elements : 
    a. ADMIN Site (**https**) that will publish + listen on channels
    b. CLIENT Side (**http**) that will only listen channels

2- Inside ADMIN Site, do we have to use this kind of connect :  WS.connect("wss://<ip>:<port>");  ?

3- Acoording to your experience, do you know what are the standard requirements for the hosting server (debian OS) to accept connections through https ? 

4- The Client SITE will have to listen to the production site channel and this one is not on https, so do we have to use WS.connect("**wss**://<ip>:<port>"); or WS.connect("**ws**://<ip>:<port>"); in this case according to your experience ?

**Comment by ProPheT777** [comment]
hello, 

> Inside ADMIN Site, do we have to use this kind of connect : WS.connect("wss://:"); ?

If your ADMIN front needs to rely on websocket yes, moreover your ADMIN is under https so it's a good pratice to secured all sub connections (like websocket), Google Chrome have strong policy with https for example : (css, fonts, js etc) must be call via https (fonts since less than 2 month), and I think in a near future they will block non secured websocket connection from https page. So https <--> wss is good :+1: 

>Acoording to your experience, do you know what are the standard requirements for the hosting server (debian OS) to accept connections through https ?

I don't really have feedback on that, i'm mainly using debian and ubuntu server in production and I don't have any problems with that. You can remove https inside your private network, it's useless and use resources for nothing. Use it only for public part

> The Client SITE will have to listen to the production site channel and this one is not on https, so do we have to use WS.connect("wss://:"); or WS.connect("ws://:"); in this case according to your experience ?

You can be on http and listen a websocket with wss or ws, their no problem with that. But it's better to have https with wss.

**Comment by michaeld23** [comment]
Thank you very much for the quick answer I appreciate it.
