### ISSUE TITLE
Check websocket before push

### ISSUE THREAD

**Issue by AntoineTesson** [GeniusesOfSymfony/WebSocketBundle#210]
Hi,

I have a question. I have set my websockets, and it's work perfectly.
But how manage Ratchet.

I explain, i put pusher with ajax notifications. So in real time  we have  notifications, and we use the old method, for users who are not connected. 

If accidentally the websocket crash, or something block or something  else, all ajax requests are becoming wrong.
Because ajax request calls a service that use the websocket.

              //La notification entraine un push
		$pusher = $this->container->get('gos_web_socket.wamp.pusher');
		$pusher->push(['msg' => 'bulles'], 'skies_notif', ['adherent' => $user->getId()]);

Is it possible to use a checking method to avoid freezing the website . Because it's very dangerous on the  production server 

Example : 
            If  ($objectPusher->somethingCheck)
{
//return true 
               $pusher = $this->container->get('gos_web_socket.wamp.pusher');
		$pusher->push(['msg' => 'bulles'], 'skies_notif', ['adherent' => $user->getId()])
}
else
{
//Pusher errors so we jump notifications in real time
}

Thanks for ur help.
Best regards.

Antoine

**Comment by AsfalothDE** [comment]
I have the same questions/problem. I need to check for websocket connection before pushing from one of my controllers. Because if the websocket is gone, the server returns error 500 for my AJAX request despite the fact, that the request itself worked just fine - only the push didn't work. I tried wrapping the push command with try/catch but to no avail. Is there a method somewhere which can check for a working websocket connection before the push?

**Comment by ProPheT777** [comment]
What kind of exception is raised? We may simply catch her ?

Other solution is to using amqp pusher is a better way because of queuing
system, you can push notification without server behind, queue will be
autimatically consumed when you will start the web socket server.

**Comment by AsfalothDE** [comment]
Hi ProPheT777, I tried catching the Exception. It is a BadResponseException and it is thrown by in vendor/gos/websocket-client/Wamp/Client.php at line 112. The message says "Could not open socket. Reason: Connection refused" which is correct of course, because the websocket is gone. I need to catch that exception or test for a valid connection first so my controller doesn't fail anymore.

Unfortunately I can't use the amqp pusher because of server limitations.

**Comment by ProPheT777** [comment]
Ok, so catch the exception is enough? do we really need to expose an API like `isConnected` which is an edge case (From my point of view) ?

**Comment by AsfalothDE** [comment]
No, catching doesn't work, I don't know why. The exception is still thrown, despite my try/catch block. isConnected would be great if it's possible... I know it's an edge case but I still would be thankful for it...

**Comment by AsfalothDE** [comment]
Strange, I tested again to catch it and now it worked. Thank you anyway for your help! 👍

**Comment by AntoineTesson** [comment]
Hi, asfalothde,  can u show me ur code, I have always the problem.  When I tried catching my push,  he returns "Could not open socket" how u jump this for continue ?  Because its a try catch under my try catch.

**Comment by AsfalothDE** [comment]
I wrote it like that:

```
try {
    $pusher = $this->container->get('gos_web_socket.wamp.pusher');
    $pusher->push($arrPush, $route, $arguments);
} catch (BadResponseException $exception) {
// Do whatever you want
}
```

**Comment by AntoineTesson** [comment]
Oh ! And its work ? I tried exactly the same code last time, and I have create the ticket for this problem with the conviction then isconnected méthod its better. OK I go back home and I will try again

**Comment by AsfalothDE** [comment]
I had the problem too at first. But I only catched the general exception, not the BadResponseException and that was it.

**Comment by AntoineTesson** [comment]
Nice one, i havent see the little difference. Have a good day =)

**Comment by maulikmmodi** [comment]
@AsfalothDE How did you define a $route in your below code? Please send me code so I can check that
`try {
    $pusher = $this->container->get('gos_web_socket.wamp.pusher');
    $pusher->push($arrPush, $route, $arguments);
} catch (BadResponseException $exception) {
// Do whatever you want
}`
