### ISSUE TITLE
Unknown "javascripts" tag.

### ISSUE THREAD

**Issue by eugestarr** [GeniusesOfSymfony/WebSocketBundle#263]
composer.json

```json
"require": {
        "php": ">=5.6",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "gos/web-socket-bundle": "^1.8",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^2.0"
},
```

After adding `{{ ws_client() }}` before closing body tag I see this error in Symfony profiler:

`Unknown "javascripts" tag.`

```md
in vendor/gos/web-socket-bundle/Resources/views/client.html.twig (line 1)

Twig_Parser->subparse(null, false)
in vendor/twig/twig/lib/Twig/Parser.php (line 79)
```

Fresh Symfony installation. First tried with twig v1.

**Comment by db306** [comment]
You are missing the assetic bundle which triggers the `{% javascripts %} {%endjavascripts}` tag.
Add this bundle in your composer require:
`"symfony/assetic-bundle": "^2.8",`

Otherwise, if you do not want to use Assetic, you can disable it in your config file by adding under gos_web_socket `assetic: false`
