### ISSUE TITLE
Socket.io client side

### ISSUE THREAD

**Issue by Kronhyx** [GeniusesOfSymfony/WebSocketBundle#300]
@ProPheT777  ¿i can use socket.io in client side? i can subscribe from socket.io to server topics????

**Comment by navalex** [comment]
Socket.io is for NodeJS Web Application, GosWebSocketBundle is for PHP Socket, with WAMP server. ;)

**Comment by ProPheT777** [comment]
humm you can use any client which support wampV1 so if socket io over wamp client exist it will work.

@navalex their is no language specification, since they communicate over a common protocol, application with wamp client can communicate to each other (java, python, js, php etc) Like php can speak to nodejs throught socket io websocket
