### ISSUE TITLE
Websocket huge delay until it works

### ISSUE THREAD

**Issue by jimiero** [GeniusesOfSymfony/WebSocketBundle#330]
Hello everyone,

I have a question if someone meets this before, when I start the websocket it delays like 24hours until the private message is showed in the message board until then have to refresh the page in order to see the message sent/received

**Comment by vlachmilan** [comment]
Are you using some kind of database (Doctrine ORM) for storing messages and then loading and sending all history?

**Comment by jimiero** [comment]
Hello @vlachmilan yes

**Comment by vlachmilan** [comment]
@jimiero I had a similar issue some time ago while using Doctrine with WebSocket. My problem was caused by misinterpreting Doctrine's functionality. In some methods, it caches the result and you have to then either: clear cached results, or: force Doctrine to not use cache at all. 

I created a question on StackOverflow where this is discussed in more details: https://stackoverflow.com/questions/51581350/php-websocket-ratchet-doesnt-fetch-newest-data-from-doctrine

Don't know if this is your case. If not, could you share a piece of your code?
