### ISSUE TITLE
Incompatible WAMP C++ clients implementation

### ISSUE THREAD

**Issue by ghost** [GeniusesOfSymfony/WebSocketBundle#337]
Hi,
I'm trying to write a C++ websocket client for my application. I tried to start with the Autobahn-cpp and also other c++ wamp client implementations but each of them needs the name of the realm to connect to and I couldn't find a way to omit this information nor to specify a realm on the server side.

**Comment by santoslluis** [comment]
I am having the same issue (but whith python and js) and I figured out why:
gos_websocket uses ratchet and it uses wamp v1 protocol, which is deprecated and removed from docs (see https://github.com/crossbario/autobahn-js/issues/166).

wamp v2 is not backwards compatible with wamp v1, so newer clients won't work.

the builtin JS integration included in this bundle works fine because it uses an older version of autobahn-js using wamp v1.

it would be interesting to specify which clients can connect with gos_websocket or to take an effort to upgrade ratchet to wamp v2 (better solution).
