### ISSUE TITLE
Modern client integrations

### ISSUE THREAD

**Issue by stipic** [GeniusesOfSymfony/WebSocketBundle#375]
I develop an application using angular 7 and i waste so much time. Just now I realized that ONLY working client is a OLD autobahn-js v0.8.2 because it's only still use WampV1, all newer versions working with WampV2, BUT Rachet is working ONLY with WampV1 and because this bundle works with Ratchet we can't use it on new modern apps.

I am interested, will this bundle planning to switch to https://github.com/voryx/Thruway instead of Ratchet because of WampV2

Any suggestions welcome.

**Comment by mbabker** [comment]
Personally, I'd suggest rather than migrating this bundle to a WampV2 library it'd be better off looking for a WampV2 oriented bundle or writing a new one using a library like Thruway.  It's essentially a different protocol and implementing support for it means replacing the library and rewriting this bundle's internals to adapt to it, I think for an existing product that leap might be a bit too big.

**Comment by stipic** [comment]
Thank you,

based on what type of project i'm working on im going to band  WS and start using

https://github.com/dunglas/mercure
