### ISSUE TITLE
Using verbose flag blocks server start

### ISSUE THREAD

**Issue by dark-matter-matters** [GeniusesOfSymfony/WebSocketBundle#379]
Using the --verbose flag when launching the webserver freezes the command. Nothing appears even after a while. Everything works fine without the flag 

`php bin/console gos:websocket:server --verbose`

**Comment by mbabker** [comment]
Do you get anything logged anywhere?  Because when I'm running locally, I always run the server with `bin/console gos:websocket:server -vvv` and never have any problems.

**Comment by dark-matter-matters** [comment]
I don't think I have logs of this. 
When using --verbose, the server does work in fact. But it does not display messages of this kind : 
```
07:00:31 DEBUG     [websocket] GET CLIENT 706
07:00:31 INFO      [websocket] User anon-14435757945cc0098f2b9e2774499052 subscribed to ligne/channel
```
It does display warnings though :
`07:00:42 WARNING   [websocket] User firewall is not configured, we have set ws_firewall by default`

**Comment by mbabker** [comment]
IIRC verbose is equivalent to 1 v, which is a little less than the 3v output.

What's the logging config for whatever env you're running this on?  It's entirely possible the log level is set to only handle warning and higher (since even with verbose output having the logging pipe to the output is still dependent on how Monolog is configured).
