### ISSUE TITLE
How stop websocket

### ISSUE THREAD

**Issue by AntoineTesson** [GeniusesOfSymfony/WebSocketBundle#390]
Hello,

How to stop /restart properly the command gos:websocket  ? 

Best regards

**Comment by mbabker** [comment]
Whatever the equivalent is to `CTRL-C` on your keyboard when you have the command running in the foreground, or the equivalent to `kill -9 <pid>` if it's running in the background or some place you can't do the `CTRL-C` method.

**Comment by ProPheT777** [comment]
Graceful : SIGINT, SIGTERM (you can signal the process, or ctrl+c) ctrl+c send a SIGINT
Hard : SIGKILL (not recommended) 

SIGTERM : `kill -15 pid`
SIGINT : `kill -2 pid`
SIGKILL : `kill -9 pid` 

SIGKILL is not recommended because it kill php itself, It mean we can't handle the signal in the user land. So, use it with caution, weird behavior incoming :D
