### ISSUE TITLE
Next stable release 

### ISSUE THREAD

**Issue by YosraHamza** [GeniusesOfSymfony/WebSocketBundle#394]
Hello, 
Thanks a lot for the bundle. I've used the 1.x version before and it was great.
When  are you willing to release the next stable version for the 2.x branch that supports the newer symfony version ?

**Comment by mbabker** [comment]
FWIW 1.x works just fine on the latest Symfony versions (both branches of the [demo app](https://github.com/GeniusesOfSymfony/WebsocketAppDemo) run Symfony 4.3 as of last update).

As for a stable 2.0 release, probably soon-ish (I'd say next few weeks).

**Comment by YosraHamza** [comment]
I already tried the 1.x but I got the error:
Attempted to load class "GetSetMethodNormalizer" from namespace "Symfony\Component\Serializer\Normalizer".
Did you forget a "use" statement for another namespace?
in vendor/gos/web-socket-bundle/Pusher/Serializer/MessageSerializer.php (line 35)

Also I found this line in the docs 
If your application requires support for Symfony versions before 3.4, use the 1.x releases of this bundle. For Symfony 3.4 or newer, use the 2.x releases.

which make me think that the old version is no more compatible with symfony4.

**Comment by mbabker** [comment]
Do you have `symfony/serializer` installed in your application?  That class has been present since at least 2.3 so you shouldn't be getting that type of message unless something is missing.

The 1.x version doesn't have much of a test suite, but like I said, the demo app is running Symfony 4.3 with both 1.x and 2.0 of this bundle so at worst the wording on the docs just needs to be improved; 1.x supports everything Symfony 2.3 and up while 2.0 only supports Symfony 3.4 and up.

**Comment by YosraHamza** [comment]
Yes tou are right. I was using the jms/serializer-bundle which was doing the serialization instead of the symfony bundle and because of that I didn't install it.
Installing it fixed the issue and now the branch is working.
Thank you.
