### ISSUE TITLE
Get subscribed users in controller

### ISSUE THREAD

**Issue by YosraHamza** [GeniusesOfSymfony/WebSocketBundle#395]
Hello, 
Thanks for the great bundle.

I was trying to get the subscribed users in controller, I tried the TopicManager and TopicResgistry but can't find a way to access the Topic object for a specific channel ( ex: chat_room/5 ) from controller so that I can loop on its subscribers as described on the PubSub Topic Handler section in docs.
As I understand, I can loop on them inside the topic and return the response in the publish, subscribe or push methods after initiating a client request, I only want to access the subscribers list without subscribing to the channel, Is that possible?

**Comment by mbabker** [comment]
It doesn't really work that way unfortunately (well, maybe you could make the system work in a way that supports this workflow, but at that point I would suggest you should directly implement the underlying [Ratchet](https://github.com/ratchetphp/Ratchet) library).

So part of the issue is the connection data is by default stored in-memory, so you only have access to the subscriber data if you're in the same process as your websocket server.  Changing the underlying storage to something that would be accessible in the context of a HTTP controller might be possible, but then you're looking at extra I/O for your websocket server to read/write that data to storage and there's probably a measurable performance impact in that.

Instead of trying to fetch the data inside a controller, I'd suggest using a JavaScript event when the page is ready to make an RPC call to the websocket server to fetch the subscribed user data.  You're still left opening a websocket connection on whatever page(s) you want to do this on, but it will be more architecturally sound than trying to rewrite critical parts of Ratchet's workflow I'd say.

```js
let websocket = WS.connect('ws://127.0.0.1:8081');

websocket.on('socket/connect', (session) => {
    session.call('subscribers', {channel: 'foo'})
        .then(
            (result) => {
                console.log('Here are my subscribers!', result);
            }
        );
    });
```

**Comment by YosraHamza** [comment]
Thanks a lot for your fast response.
It's clear now how it's actually working, I will re-think again about the logic to achieve what I wanted from the client side as you mentioned.
