### ISSUE TITLE
 [JS] Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by theodorDiaconu** [GeniusesOfSymfony/WebSocketBundle#45]
When including {{ ws_client() }} 

Uncaught ReferenceError: module is not defined

What am I missing ?

**Comment by cristhianfernandez01** [comment]
Hello theodorDiaconu. You have installed Assetic?If so you should also run the following command according to the documentation:
````````````````````````````````````````````
php app/console assetic:dump --env=prod --no-debug
````````````````````````````````````````````

**Comment by theodorDiaconu** [comment]
@cristhianfernandez01 yep I always use that because the project is 1 year old. I couldn't figure it out but using {{ clank_client() }} worked (the old version of this Bundle). In the end I realized that WAMP v1 is old school and ratchet doesn't implement v2 yet.

**Comment by ProPheT777** [comment]
Yes ratchet doesn't support wamp V2, and ratchet will be drop soon as possible and replaced by my own server stack but I'll not support wamp V2 and keep wamp v1 because Wamp v2 is too heavy (a big overhead) and out of scope for web application, he resolve a lot of problematic that we won't (as messaging protocol). So if you are looking for wamp v2 support i'm sorry but this bundle will not support it :(
