### ISSUE TITLE
How to create notifications from PHP

### ISSUE THREAD

**Issue by benr77** [GeniusesOfSymfony/WebSocketBundle#60]
The docs have several examples on how to publish a notification from Javascript but how is this done from PHP?

Is it using the Pushers such as the WAMP pusher service? I've been poking around the docs for ages now and it's really not clear.

Thanks

**Comment by ProPheT777** [comment]
Hi,

Yes in order to push from PHP you must use a Pusher (via zmq, amqp or wamp). 

The docs is just here : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/Pusher.md

I'm not able to help you if you do not provide more explantion about your problem :( 

What problem is blocking you or what is unclear ? And Can you give me advice in order to improve the docs ?

Thx

**Comment by benr77** [comment]
Hi. Sorry for the delay in responding I have been travelling. No specific problem to help with. Thanks for confirming that the Pusher is the way to send from PHP.

All the documentation needs is a note somewhere (perhaps in the Client Setup page) that in order to send from PHP please refer to the Pusher Integration documentation page
