### ISSUE TITLE
List/Count users in each room

### ISSUE THREAD

**Issue by North73** [GeniusesOfSymfony/WebSocketBundle#61]
Hi,

I'm trying to count users in each room;

For example i got room1&room2:
chat/channel/room1
chat/channel/room2

Now i want on my listpage, the available user in each room.

is this possible??

Thanks!!

**Comment by ProPheT777** [comment]
Yes you can and it's easy. Just increment decrement a counter in data store (redis, mysql) from your topic and retrieve the value in a controller. 
Le 14 sept. 2015 20:05, North73 <notifications@github.com> a écrit :Hi,

I'm trying to count users in each room;

For example i got room1&room2:
chat/channel/room1
chat/channel/room2

Now i want on my listpage, the available user in each room.

is this possible??

Thanks!!

**Comment by North73** [comment]
Ok, thanks for the quick response.

But it is not possible by using the "pubsub router".

So when a user Subscribe on a channel, i can count the other channels?

**Comment by ProPheT777** [comment]
In fact you have many ways to achieve that. I think the best option is to implement a behavior on your topic. You can use a decorator pattern to wrap a topic and add the ability to update a counter. 
Imo it's the best solution that I have and  easier. 
The pubsub router is just a router who dispatch connection across topic.
In most of case you should have external counter in order to access it from your application because they are isolated.
Another possible way is to use RPC to retrieve the current number of people in a room.
Le 15 sept. 2015 08:57, North73 <notifications@github.com> a écrit :Ok, thanks for the quick response.

But it is not possible by using the "pubsub router".

So when a user Subscribe on a channel, i can count the other channels?

**Comment by North73** [comment]
thx i have used your first solution ;-)
