### ISSUE TITLE
Deployment on server

### ISSUE THREAD

**Issue by mitke013** [GeniusesOfSymfony/WebSocketBundle#7]
First, I want to thank you for this awesome bundle. I wasn't able to set Clank but this one was pretty simple; although with the big help from #4 

But how to deploy on live site? When I run gos:server, console is locked and I can't exit it without ctrl+c. 

When the program is updated, how to stop previous gos:server and rerun it?

**Comment by gittix09** [comment]
I'm also interested!!
P.s. You're welcome for issue #4

**Comment by ProPheT777** [comment]
Hi, 
Thank you very much !

Manage linux process is not directly to this bundle.

You can take a look to http://supervisord.org, and here an example of symfony2 command integration http://jmsyst.com/bundles/JMSJobQueueBundle/master/installation#setting-up-supervisord.

You also use https://github.com/ivan1986/SupervisorBundle to manage/run process from symfony2 command directly. 

And webinterface for easy management (instead of cli command) http://codesamplez.com/management/supervisord-web-interface-and-plugin

In nutshell supervisord is process manager.

**Comment by mitke013** [comment]
Thank you, and sorry for offtopic questions. I am linux noob and supervisor bundle worked liked magic.

**Comment by ProPheT777** [comment]
No problem !
