### ISSUE TITLE
How set server close callback and how send and receive msg like ratchet do

### ISSUE THREAD

**Issue by tuxado** [GeniusesOfSymfony/WebSocketBundle#77]
Hi 

How performe à ws server close évent i read that ratchet have server  callback passes on the constructor to be executed when the server close

How to use thé server to send and receive messages from clients because thé docs arent clear if i understand i will rewrite wampapplication file to add onmessage évent and rewrite thé service that call thé websocketserver ? 

Tkx

**Comment by ProPheT777** [comment]
Hi, 

You don't need to rewrite if you want add a callback when the server close. 

You have to create a listener like this : 

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Event/StartServerListener.php
registered here : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/config/services/services.yml#L153

And do 

```php
$server = $event->getServer();
$server->on('end', function(){
   // ... your stuff.
});
```

And the event `gos_web_socket.server_launched` is good, because this listener is call when the server start in order to attach your ending callback to the loop.

**Comment by ProPheT777** [comment]
May should I add documentation about that

**Comment by tuxado** [comment]
Hi, Tkx for your reply, i rewrite the bundle for adapting it to my needs and i add an websocketapplication.php with onmessage event to replace de wamp one to connecte the sever with a desktop applications using websocket only i dont know if its the good way :)
