### ISSUE TITLE
Only allow current user to subscribe to his channel.

### ISSUE THREAD

**Issue by Xyr2** [GeniusesOfSymfony/WebSocketBundle#82]
Hi there,

I got a specific channel for every user, like /push/{user} and already set up successfully the session handling.
Now I've got the question, where to check the websocket user against the security context on subscription, so that only the current user can subscribe on his channel?

Thanks for your help.. :)

**Comment by Xyr2** [comment]
Ah and I forgot to ask, where can I check to only let registered users connect to the websocket server?

**Comment by The-Don-Himself** [comment]
This is what you are looking for, it is in the docs:)

        $user1 = $this->clientManipulator->findByUsername($topic, 'user1');
        if (false !== $user1) {
            $topic->broadcast('message', array(), array($user1['connection']->WAMP->sessionId));
        }

The if part check for the specific condition you are looking for, if it has helped you please close this issue now.

**Comment by ProPheT777** [comment]
Hey, 

The solution of @The-Don-Himself works fine and you need help ?

**Comment by Xyr2** [comment]
I'll try this this evening and will close the issue or reply, if I could need some more help. Thanks.. :)

**Comment by Xyr2** [comment]
Unfortunately this didn't helped me. Isn't this just for sending a message to a specific user? Thats what the docs are saying.
I need something like:
```php
$user = $this->clientManipulator->getClient($connection)->getUsername();
if ($user == lastPartOfTopic) {       // last part is   {user} in my routing   /push/{user}
  subscribe
else {
   dont let me in...
}
```
And I wonder if the TopicHandler service is the right place to do this? Because the onSubcribe function triggers after someone subscribed, doesnt it? But I dont wont to let someone subscribe that is not allowed to subscribe to this channel.

And what about the other thing, only letting registered users connect to WS?
Hope you understand me, and thank you very much for your help! Very appreciated :)

**Comment by The-Don-Himself** [comment]
I am not quite sure if I totally understand you but I will try assist with the knowledge I have.

It seems like you are asking how to prevent unauthorized access. There are 2 ways I see this happening. One is more secure but requires more work and server resources and the other is less secure but only a hacker can know that.

Method 1.
Get the username of the person you want to communicate with. I am assuming you are using FOSUserBundle so querying for a username is simple i.e 
$username = null;
$user = $this->getUser();
if($user) { $username = $user->getUsername();}
if($username){
// now you can do something with it like
    $user1 = $this->clientManipulator->findByUsername($topic, $username);
    if (false !== $user1) { // This username is connected
        $topic->broadcast('message', array(), array($user1['connection']->WAMP->sessionId)); // Send him messages via sockets to all open browsers tabs supporting it
    }
}

This method means that you are hitting your db to query for the user object on every page load and on every socket message you want to send, not very nice performance wise so if it's for chatting, every chat message sent will incur at least 1 db hit and probably more if you are persisting messages to db, avoid this method.

Method 2.
Use twig features. Example
{% if app.request.server.get("HTTP_CF_IPCOUNTRY") %}
	{% set country_iso2 = app.request.server.get("HTTP_CF_IPCOUNTRY") %}
{% else %}
	{% set country_iso2 = 'XX' %}
{% endif %}
{% if app.user %}
	{% set socket = app.user.id %}
{% else %}
	{% set socket = country_iso2 %}
{% endif %}

then someone else

{% block javascripts %}
	{{ parent() }}
    {{ ws_client() }}
    <script type="text/javascript">
	$(document).ready(function() {
        var websocket = WS.connect("ws://localhost:1337");

        websocket.on("socket/connect", function(session){
            session.subscribe("websocket/{{ socket }}", function(uri, payload){
                var json = $.parseJSON(payload);
				$.globalEval(json.msg.data);
			});

//            session.publish("websocket/{{ socket }}", {msg: "This is a message!"});

        });

        websocket.on("socket/disconnect", function(error){
            //error provides us with some insight into the disconnection: error.reason and error.code

            console.log("Disconnected for " + error.reason + " with code " + error.code);
        });
    });
    </script>

Note: this is an example for my own web app, I am currently using Cloudflare to accelerate and protect my site and one of the benefits is that I get to know which country a visitor is coming from in a 2 leter country iso format. In this example, all registered users are subscribed to a channel using user id while no-registered or logged in members are subscribed to a channel for their country.

For you use case I you can consider putting the socket connect statements within the twig conditional block for example

{% if app.user %}
    {{ ws_client() }}
    <script type="text/javascript">
	$(document).ready(function() {
        var websocket = WS.connect("ws://localhost:1337");

        websocket.on("socket/connect", function(session){
            session.subscribe("websocket/{{ socket }}", function(uri, payload){
                var json = $.parseJSON(payload);
				$.globalEval(json.msg.data);
			});

//            session.publish("websocket/{{ socket }}", {msg: "This is a message!"});

        });

        websocket.on("socket/disconnect", function(error){
            //error provides us with some insight into the disconnection: error.reason and error.code

            console.log("Disconnected for " + error.reason + " with code " + error.code);
        });
    });
    </script>
{% endif %}

This way, only logged in users get to be subscribed to a channel, it is possible for a hacker to try and subscribe to a channel manually i.e from outside but very few people will do that and besides GOSWebsocketBundle has a way to confirm the origin of the requests.

I prefer method 2 because, when you want to send a message all you have to do is something like

$pusher = $this->container->get('gos_web_socket.pusher');
$pusher->push(['msg' => $data], 'web_sockets_notifications', ['socket' => $user_id]);

from a controller, you probably do not even need to query the db from the $user_id if it was sent, in fact if it is chat messages, you can queue them using RabbitMQBundle to be persisted to db later hence truly using sockets for instantaneous real time communication.

This is just an example of how I am using it, the possibilities are endless.

**Comment by The-Don-Himself** [comment]
@Xyr2 Has this helped you? If so please close this issue to enhance maintainability of the issues list, you can always reopen or add comments later.

**Comment by Xyr2** [comment]
Yes, thank you very much!

**Comment by Xyr2** [comment]
Hey, sorry I have to reopen this again.. ;)

I think we have a little understanding problem, I try to explain it again, because I think its not that hard to achieve what I want to do, I just don't know where to do this.

So here is what I got:
a route like /push/{username} - for example for user "Franz" I have the room /push/Franz
Franz subscribes to the room /push/Franz and all the other users that want to send him a message publish to /push/Franz
So at the moment everyone could open Firebug and manually subscribe to the channel /push/Franz, listening to all messages other users publish to /push/Franz
So all I have to do to prevent this is to check if the connected client's username is the same as the channel he wants to subscribe to. 
This shouldn't be very hard, but I just don't know in which file I should do the check. In my custom TopicHandler I got the onSubscribe action, but all I can do there is to broadcast something AFTER a user subscribed to a channel, so I have to do this check before someone subscribes to a channel. My only question is where to do so.. :)

Hope everything is clear now. Thanks for your patience and help!

**Comment by The-Don-Himself** [comment]
@Xyr2 Reopening is fine and I will try to help where I can.

''''
a route like /push/{username} - for example for user "Franz" I have the room /push/Franz
Franz subscribes to the room /push/Franz and all the other users that want to send him a message publish to /push/Franz
''''
This is correct as far as I know.
''''
So at the moment everyone could open Firebug and manually subscribe to the channel /push/Franz, listening to all messages other users publish to /push/Franz
''''
Again, this is correct as far as I know, although, not many would do this but you are right that a few people with malicious intentions might, I personally solve this by not sending any sensitive information via sockets but let me explain how to help you solve it in the way you want.

''''
So all I have to do to prevent this is to check if the connected client's username is the same as the channel he wants to subscribe to. 
''''
Yes, this is the way you want to ensure that every message that goes to channel /push/Franz is actually reaching username Franz and only Username Franz.
''''
This shouldn't be very hard, but I just don't know in which file I should do the check. In my custom TopicHandler I got the onSubscribe action, but all I can do there is to broadcast something AFTER a user subscribed to a channel, so I have to do this check before someone subscribes to a channel. My only question is where to do so.. :)
''''
It is not really about which file but more of every time you want to send/broadcast a message whether from Topic, Command, Listener or Controller, what you have to do is a 2-3 step process.

First, acquire the username you want to send message to. The example I gave you above works well eg.
''''
$username = null;
$user = $this->getUser();
if($user) { $username = $user->getUsername();}
''''
Up until here we have the Username of the person we want to send a message to. You might achieve this via other methods.

After getting the username, check to make sure it exists eg 
''''
if($username){
''''
After confirming this condition to be true, we now look to see whether the given username is subscribed to the topic(channel) we want
''''
$is_username_subscribed = $this->clientManipulator->findByUsername($topic, $username);
''''
Check whether the said condition is true meaning it is not false
''''
    if (false !== $user1) { // This username is connected
''''
If not false then the user (found by username) is connected, we uniquely identify him/her by the logged in session id and therefore can broadcast a message eg
''''
        $topic->broadcast('message', array(), array($user1['connection']->WAMP->sessionId)); 
''''

First try to really understand this process. If you have then you must realise a few things.

1.) If using this from a Topic, then you cannot (in my view) check for these conditions before someone subscribes, in other words, someone say Brian will first subscribe to /push/Franz then you can check for these conditions thereafter and decided to send messages to /push/Franz but only to Username Franz so Brian will not receive even though he has subscribed.

2.) From outside a topic, there is no default way (in my view) to check whether anyone is Subscribed to /push/Franz, so you might get a failed broadcast even though you first checked to send only to username Franz. My current solution to this is by using a fast in memory database - Redis - to store the number count every time someone subscribes or unsubscribes to a channel.

Hope this helps.

**Comment by Xyr2** [comment]
Hey, thanks for your fast reply.

So I have to check this on every message someone broadcasts. That is indeed not the best performing way.. :) Any idea where outside a topic I could check on subscription? This would be the best way in my opinion, only having to access the database on page reload and not on every message. Maybe somewhere in the Router?
Where did you do your check with the number count? I assume you check if count is > 0, no one else can subscribe? But where?

Anyway, thanks again for your detailed help!

**Comment by The-Don-Himself** [comment]
````
Hey, thanks for your fast reply.
````
You are welcome :)
````
So I have to check this on every message someone broadcasts. That is indeed not the best performing way.. :)
````
Indeed, but if you properly utilize database caching strategies then the performance hit is not very significant almost negligible to be honest. Just make sure you 1.) Create an index on the username column, 2.) Cache user data in memory using either apcu (best performer but should be used for single servers only), redis (best overall) or memcached 3.) If using redis or memcached ensure that the data is as close to your server as possible to reduce network latency, I use redis master-slave asynchronous replication. 

Doing the above showed that querying for each username took less than 2ms each, I profiled it. But if you don't do this then you can really suffer performance degradation so I advise against it.

````
Any idea where outside a topic I could check on subscription? This would be the best way in my opinion, only having to access the database on page reload and not on every message. Maybe somewhere in the Router?
````

Not possible, you can use the Symfony firewall to ensure that only users with certain roles like Role_User or Role_Admin access certain parts http://symfony.com/doc/current/book/security.html but to check whether a registered user is who he says he is before an action must (in my view) involve some sort of lookup probably from a database.

````
Where did you do your check with the number count? I assume you check if count is > 0, no one else can subscribe? But where?
````
No, I do not use it in this way, because 1.) if someone opens up many tabs in the same browser, or uses many devices (mobile & tabs) then the count will be 4,5,6 or more but all for the same person so I wouldn't want to disallow this. I use the count only to know whether I should send a broadcast from a controller/command or not. Eg, if user is online then count is greater than 1, thus send notification message but if offline then counter is 0 thus save message to database for viewing later. Something like that.

**Comment by yamilovs** [comment]
@Xyr2, hello!

I'll try to explain how i just did it. In my application for each user i create a notification token. For sample - my token is "I-pEaHWk7jPdPiXqcfMJ8i7QAf9KUpHBhOoWO0Md2us" and i think its realy hard to guess.

Also on "onSubscribe" topic method i do:
```
public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request) {
    $userToken = $this->topicManager->getUser($connection)->getNotificationSettings()->getToken();
    $token = $request->getAttributes()->get('token');
    if ($userToken != $token) $connection->close();
}
```
where $this->topicManager - a simple manager wich get User Entity from doctrine, based on WebSocket clientManipulator. For sample method in this manager

```
public function getUser(ConnectionInterface $connection) {
    $repository = $this->entityManager->getRepository('MySampleBundle:User');
    $wsUser = $this->clientManipulator->getClient($connection);
    return $repository->find($wsUser->getId());
}
```

I hope this will help you. or anyone else)

**Comment by novacp** [comment]
ProPheT is doing it the right way. Just one question about it: When I call $connection->close(), autobahnjs is automatically trying to reconnect the websocket. Souldn't you better just remove the connection of the topic, or how do you prevent the auto reconnect?

**Comment by klodoma** [comment]
I like the idea .2 proposed by @The-Don-Himself . 
Though, I have extended it a bit to check if the user is valid. 

Practically, on onSubscribe I check if the user is logged in and if the matched route IS really the "allowed" route. For example, if a "hacker" or another user tries to subscribe to the channel, the subscription just gets dropped. 

I do not close the connection, cause that causes a retry, though I still need to dig into this aspect. 

My Topic Code: 

```
<?php

namespace MappsBundle\Topic;

use Ratchet\ConnectionInterface;
use Gos\Bundle\WebSocketBundle\Client\ClientManipulatorInterface;
use Gos\Bundle\WebSocketBundle\Router\WampRequest;
use Gos\Bundle\WebSocketBundle\Topic\TopicInterface;
use Ratchet\Wamp\Topic;
use Symfony\Component\Security\Core\Security;
use FOS\UserBundle\Model\UserInterface;

/**
 * Class UserNotificationTopic
 * @package MappsBundle\Topic
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 */
class UserNotificationTopic implements TopicInterface
{
    /**
     * @var ClientManipulatorInterface
     */
    protected $clientManipulator;

    /**
     * @var Security
     */
    protected $security;

    /**
     * @param ClientManipulatorInterface $clientManipulator
     * @param Security $security
     */
    public function __construct(ClientManipulatorInterface $clientManipulator, Security $security)
    {
        $this->clientManipulator = $clientManipulator;
        $this->security = $security;
    }

    /**
     * Returns true if the user is a valid user
     *
     * @param UserInterface|string|null $user
     * @return bool
     */
    protected function isValidUser($user)
    {
        //if required do other checks, like permissions etc...
        return ($user && $user instanceof UserInterface);
    }

    /**
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     */
    public function onSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this is the user that sends the request
        $user = $this->clientManipulator->getClient($connection);

        //if there is no authenticated user - drop this subscription
        if (!$this->isValidUser($user)) {
            //drop subscription
            $topic->remove($connection);
            return;
        }

        //get the matched route
        $matched = $request->getMatched();

        //the route pattern is : notification/{username}
        $shouldMatch = sprintf('notification/%s', $user->getUsername());

        //dump($matched, $shouldMatch, $matched == $shouldMatch);

        if ($matched !== $shouldMatch) {
            //drop subscription
            $topic->remove($connection);
            return;
        }

        $topic->broadcast(['msg' => $connection->resourceId . " has  joined " . $topic->getId()]);
    }

    /**
     * This will receive any UnSubscription requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     */
    public function onUnSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request)
    {
        //this will broadcast the message to ALL subscribers of this topic.
        $topic->broadcast(['msg' => $connection->resourceId . " has left " . $topic->getId()]);
    }

    /**
     * This will receive any Publish requests for this topic.
     *
     * @param ConnectionInterface $connection
     * @param Topic $topic
     * @param WampRequest $request
     * @param $event
     * @param array $exclude
     * @param array $eligible
     */
    public function onPublish(ConnectionInterface $connection, Topic $topic, WampRequest $request, $event, array $exclude, array $eligible)
    {
        $topic->broadcast([
            'msg' => $event
        ]);
    }

    /**
     * Like RPC is will use to prefix the channel
     * @return string
     */
    public function getName()
    {
        return 'user.notifications.topic';
    }
}
```

and in routing.yml:

```
user_notification:
    channel: notification/{username}
    handler:
        callback: 'user.notifications.topic' #related to the getName() of your topic

```
